# Name: Taaha Bin Mohsin

version: "3"
services:
  user_server:
    build: ./US
    ports:
      - "8080:8080"
    depends_on:
      - authoritative_server
      - fibonacci_server
    environment:
      - AS_IP=authoritative_server
      - AS_PORT=53533
    networks:
      - dns_network

  fibonacci_server:
    build: ./FS
    ports:
      - "9090:9090"
    networks:
      - dns_network

  authoritative_server:
    build: ./AS
    ports:
      - "53533:53533/udp"
    networks:
      - dns_network

networks:
  dns_network:
    driver: bridge
